# Logging configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: INFO
  # Log format string
  format: '%(asctime)s - %(levelname)s - %(message)s'
  # Log file configuration
  file:
    # Enable file logging
    enabled: false
    # Log file path
    path: 'logs/app.log'
    # Maximum log file size in bytes
    max_size: 10485760 # 10MB
    # Number of backup files to keep
    backup_count: 5
    # Log format for file output (JSON)
    format: 'json'

# Webhook configuration
webhook:
  # Rate limiting configuration
  rate_limit:
    # Maximum requests per minute
    requests_per_minute: 60
    # Burst size
    burst_size: 10

# Tracking services configuration
users:
  # Replace with your username
  your_username:
    # TVTime configuration
    tvtime:
      # Your TVTime email
      username: 'your-email@example.com'
      # Your TVTime password
      password: 'your-password'
    # TrackTV (Trakt.tv) configuration
    tracktv:
      # Your Trakt.tv client ID
      client_id: 'your-client-id'
      # Your Trakt.tv client secret
      client_secret: 'your-client-secret'
      # Your Trakt.tv authorization code
      code: 'your-auth-code'
      # Your Trakt.tv redirect URI
      redirect_uri: 'http://127.0.0.1:5000'

# Retry configuration for API calls
retry:
  # Maximum number of retries
  max_retries: 3
  # Initial delay between retries in seconds
  initial_delay: 1
  # Maximum delay between retries in seconds
  max_delay: 10
  # Exponential backoff factor
  backoff_factor: 2
  # Jitter factor (0-1) to add randomness to delays
  jitter: 0.1
